# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
from __future__ import annotations

import dataclasses
from typing import Any


@dataclasses.dataclass()
class Recommendation:
    recommendation_id: Any
    patient_id: Any
    recommendation: Any
    timestamp: Any
